# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6cb24b83adb7fb55254114f9e95445407283dff32a746677f79ea5be454062c5c621a120ad5f5af6a70bcb25090065bfcde229800a3863474b7776f5e4ce00

test:
  secret_key_base: 8097c4ac524aae9088d89a282af89bfb61fbabe4c372c073c202e2ba654235681ce4007b64037f522dbd3ab95067c46987b9aa47c3140200d353ac0d51c1fd23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
